language: android
jdk: oraclejdk8
sudo: false

notifications:
    email:
        - olivierisoares@gmail.com

android:
    components:
        - platform-tools
        - build-tools-26.0.1
        - android-23
        - extra-android-m2repository
script:
    - ./gradlew build jacocoTestReport

before_install:
    - chmod +x gradlew
    - yes | sdkmanager "platforms;android-26"

after_success:
    - bash <(curl -s https://codecov.io/bash)

branches:
    only:
        - travis-test