language: android
jdk: oraclejdk8
sudo: false

notifications:
    email:
        - olivierisoares@gmail.com

android:
    components:
        - platform-tools
        - build-tools-27.0.3
        - android-23
        - extra-android-m2repository
script:
    - ./gradlew build
    - ./gradlew connectedCheck -PdisablePreDex --stacktrace

before_install:
    - chmod +x gradlew
    - pip install --user codecov    #Install codecov

after_success:
    - codecov                       #Run codecov

after_failure: "cat $TRAVIS_BUILD_DIR/app/build/outputs/lint-results-debug.xml"

branches:
    only:
        - master