ignore:
- '**/R.class'
- '**/R$*.class'
- '**/BuildConfig.*'
- '**/Manifest*.*'
- 'android/**/*.*'
- 'io/realm/**/*.*'
- '**/*_Impl*'
- '**/*_MembersInjector.class'
- '**/Dagger*Component.class'
- '**/Dagger*Component$Builder.class'
- '**/*Module_*Factory.class'
- '**/*Realm**'
- '**/FavoritesRepository.class'
- '**/*Test*.*'
- '**/**_Factory**'